export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN';
export const TOGGLE_ALERT_MESSAGE = 'TOGGLE_ALERT_MESSAGE';

export const GET_PAGES_REQUEST = 'GET_PAGES_REQUEST';
export const GET_PAGES_SUCCESS = 'GET_PAGES_SUCCESS';
export const GET_PAGES_FAILURE = 'GET_PAGES_FAILURE';
