export const STATUS_SUCCESS = 'success';
export const STATUS_FAILURE = 'failure';
export const STATUS_LOADING = 'loading';
export const STATUS_IDLE = 'idle';

export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN';
export const TOGGLE_ALERT_MESSAGE = 'TOGGLE_ALERT_MESSAGE';

/**
 * Login
 */
export const POST_LOGIN_IDLE = 'POST_LOGIN_IDLE';
export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

/**
 * Logout
 */
export const POST_LOGOUT_IDLE = 'POST_LOGOUT_IDLE';
export const POST_LOGOUT_REQUEST = 'POST_LOGOUT_REQUEST';
export const POST_LOGOUT_SUCCESS = 'POST_LOGOUT_SUCCESS';
export const POST_LOGOUT_FAILURE = 'POST_LOGOUT_FAILURE';

/**
 * Pages
 */
export const GET_PAGES_IDLE = 'GET_PAGES_IDLE';
export const GET_PAGES_REQUEST = 'GET_PAGES_REQUEST';
export const GET_PAGES_SUCCESS = 'GET_PAGES_SUCCESS';
export const GET_PAGES_FAILURE = 'GET_PAGES_FAILURE';

export const GET_PAGE_IDLE = 'GET_PAGE_IDLE';
export const GET_PAGE_REQUEST = 'GET_PAGE_REQUEST';
export const GET_PAGE_SUCCESS = 'GET_PAGE_SUCCESS';
export const GET_PAGE_FAILURE = 'GET_PAGE_FAILURE';

export const POST_PAGE_IDLE = 'POST_PAGE_IDLE';
export const POST_PAGE_REQUEST = 'POST_PAGE_REQUEST';
export const POST_PAGE_SUCCESS = 'POST_PAGE_SUCCESS';
export const POST_PAGE_FAILURE = 'POST_PAGE_FAILURE';


/**
 * Products
 */
export const GET_PRODUCTS_IDLE = 'GET_PRODUCTS_IDLE';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const GET_PRODUCT_IDLE = 'GET_PRODUCT_IDLE';
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const POST_PRODUCT_IDLE = 'POST_PRODUCT_IDLE';
export const POST_PRODUCT_REQUEST = 'POST_PRODUCT_REQUEST';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const POST_PRODUCT_FAILURE = 'POST_PRODUCT_FAILURE';


/**
 * Page categories
 */
export const GET_PAGE_CATEGORIES_IDLE = 'GET_PAGE_CATEGORIES_IDLE';
export const GET_PAGE_CATEGORIES_REQUEST = 'GET_PAGE_CATEGORIES_REQUEST';
export const GET_PAGE_CATEGORIES_SUCCESS = 'GET_PAGE_CATEGORIES_SUCCESS';
export const GET_PAGE_CATEGORIES_FAILURE = 'GET_PAGE_CATEGORIES_FAILURE';

export const GET_PAGE_CATEGORY_IDLE = 'GET_PAGE_CATEGORY_IDLE';
export const GET_PAGE_CATEGORY_REQUEST = 'GET_PAGE_CATEGORY_REQUEST';
export const GET_PAGE_CATEGORY_SUCCESS = 'GET_PAGE_CATEGORY_SUCCESS';
export const GET_PAGE_CATEGORY_FAILURE = 'GET_PAGE_CATEGORY_FAILURE';

export const POST_PAGE_CATEGORY_IDLE = 'POST_PAGE_CATEGORY_IDLE';
export const POST_PAGE_CATEGORY_REQUEST = 'POST_PAGE_CATEGORY_REQUEST';
export const POST_PAGE_CATEGORY_SUCCESS = 'POST_PAGE_CATEGORY_SUCCESS';
export const POST_PAGE_CATEGORY_FAILURE = 'POST_PAGE_CATEGORY_FAILURE';

/**
 * Page sub categories
 */
export const GET_PAGE_SUB_CATEGORIES_IDLE = 'GET_PAGE_SUB_CATEGORIES_IDLE';
export const GET_PAGE_SUB_CATEGORIES_REQUEST = 'GET_PAGE_SUB_CATEGORIES_REQUEST';
export const GET_PAGE_SUB_CATEGORIES_SUCCESS = 'GET_PAGE_SUB_CATEGORIES_SUCCESS';
export const GET_PAGE_SUB_CATEGORIES_FAILURE = 'GET_PAGE_SUB_CATEGORIES_FAILURE';

export const GET_PAGE_SUB_CATEGORY_IDLE = 'GET_PAGE_SUB_CATEGORY_IDLE';
export const GET_PAGE_SUB_CATEGORY_REQUEST = 'GET_PAGE_SUB_CATEGORY_REQUEST';
export const GET_PAGE_SUB_CATEGORY_SUCCESS = 'GET_PAGE_SUB_CATEGORY_SUCCESS';
export const GET_PAGE_SUB_CATEGORY_FAILURE = 'GET_PAGE_SUB_CATEGORY_FAILURE';

export const POST_PAGE_SUB_CATEGORY_IDLE = 'POST_PAGE_SUB_CATEGORY_IDLE';
export const POST_PAGE_SUB_CATEGORY_REQUEST = 'POST_PAGE_SUB_CATEGORY_REQUEST';
export const POST_PAGE_SUB_CATEGORY_SUCCESS = 'POST_PAGE_SUB_CATEGORY_SUCCESS';
export const POST_PAGE_SUB_CATEGORY_FAILURE = 'POST_PAGE_SUB_CATEGORY_FAILURE';


/**
 * Product categories
 */
export const GET_PRODUCT_CATEGORIES_IDLE = 'GET_PRODUCT_CATEGORIES_IDLE';
export const GET_PRODUCT_CATEGORIES_REQUEST = 'GET_PRODUCT_CATEGORIES_REQUEST';
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS';
export const GET_PRODUCT_CATEGORIES_FAILURE = 'GET_PRODUCT_CATEGORIES_FAILURE';

export const GET_PRODUCT_CATEGORY_IDLE = 'GET_PRODUCT_CATEGORY_IDLE';
export const GET_PRODUCT_CATEGORY_REQUEST = 'GET_PRODUCT_CATEGORY_REQUEST';
export const GET_PRODUCT_CATEGORY_SUCCESS = 'GET_PRODUCT_CATEGORY_SUCCESS';
export const GET_PRODUCT_CATEGORY_FAILURE = 'GET_PRODUCT_CATEGORY_FAILURE';

export const POST_PRODUCT_CATEGORY_IDLE = 'POST_PRODUCT_CATEGORY_IDLE';
export const POST_PRODUCT_CATEGORY_REQUEST = 'POST_PRODUCT_CATEGORY_REQUEST';
export const POST_PRODUCT_CATEGORY_SUCCESS = 'POST_PRODUCT_CATEGORY_SUCCESS';
export const POST_PRODUCT_CATEGORY_FAILURE = 'POST_PRODUCT_CATEGORY_FAILURE';

/**
 * Product categories
 */
export const GET_PRODUCT_SUB_CATEGORIES_IDLE = 'GET_PRODUCT_SUB_CATEGORIES_IDLE';
export const GET_PRODUCT_SUB_CATEGORIES_REQUEST = 'GET_PRODUCT_SUB_CATEGORIES_REQUEST';
export const GET_PRODUCT_SUB_CATEGORIES_SUCCESS = 'GET_PRODUCT_SUB_CATEGORIES_SUCCESS';
export const GET_PRODUCT_SUB_CATEGORIES_FAILURE = 'GET_PRODUCT_SUB_CATEGORIES_FAILURE';

export const GET_PRODUCT_SUB_CATEGORY_IDLE = 'GET_PRODUCT_SUB_CATEGORY_IDLE';
export const GET_PRODUCT_SUB_CATEGORY_REQUEST = 'GET_PRODUCT_SUB_CATEGORY_REQUEST';
export const GET_PRODUCT_SUB_CATEGORY_SUCCESS = 'GET_PRODUCT_SUB_CATEGORY_SUCCESS';
export const GET_PRODUCT_SUB_CATEGORY_FAILURE = 'GET_PRODUCT_SUB_CATEGORY_FAILURE';

export const POST_PRODUCT_SUB_CATEGORY_IDLE = 'POST_PRODUCT_SUB_CATEGORY_IDLE';
export const POST_PRODUCT_SUB_CATEGORY_REQUEST = 'POST_PRODUCT_SUB_CATEGORY_REQUEST';
export const POST_PRODUCT_SUB_CATEGORY_SUCCESS = 'POST_PRODUCT_SUB_CATEGORY_SUCCESS';
export const POST_PRODUCT_SUB_CATEGORY_FAILURE = 'POST_PRODUCT_SUB_CATEGORY_FAILURE';


/**
 * Product categories
 */
export const GET_PRODUCT_OPTIONS_IDLE = 'GET_PRODUCT_OPTIONS_IDLE';
export const GET_PRODUCT_OPTIONS_REQUEST = 'GET_PRODUCT_OPTIONS_REQUEST';
export const GET_PRODUCT_OPTIONS_SUCCESS = 'GET_PRODUCT_OPTIONS_SUCCESS';
export const GET_PRODUCT_OPTIONS_FAILURE = 'GET_PRODUCT_OPTIONS_FAILURE';

export const GET_DISTINCT_PRODUCT_OPTIONS_IDLE = 'GET_DISTINCT_PRODUCT_OPTIONS_IDLE';
export const GET_DISTINCT_PRODUCT_OPTIONS_REQUEST = 'GET_DISTINCT_PRODUCT_OPTIONS_REQUEST';
export const GET_DISTINCT_PRODUCT_OPTIONS_SUCCESS = 'GET_DISTINCT_PRODUCT_OPTIONS_SUCCESS';
export const GET_DISTINCT_PRODUCT_OPTIONS_FAILURE = 'GET_DISTINCT_PRODUCT_OPTIONS_FAILURE';

export const GET_PRODUCT_SUGGEST_IDLE = 'GET_PRODUCT_SUGGEST_IDLE';
export const GET_PRODUCT_SUGGEST_REQUEST = 'GET_PRODUCT_SUGGEST_REQUEST';
export const GET_PRODUCT_SUGGEST_SUCCESS = 'GET_PRODUCT_SUGGEST_SUCCESS';
export const GET_PRODUCT_SUGGEST_FAILURE = 'GET_PRODUCT_SUGGEST_FAILURE';

export const GET_PRODUCT_OPTION_IDLE = 'GET_PRODUCT_OPTION_IDLE';
export const GET_PRODUCT_OPTION_REQUEST = 'GET_PRODUCT_OPTION_REQUEST';
export const GET_PRODUCT_OPTION_SUCCESS = 'GET_PRODUCT_OPTION_SUCCESS';
export const GET_PRODUCT_OPTION_FAILURE = 'GET_PRODUCT_OPTION_FAILURE';

export const POST_PRODUCT_OPTION_IDLE = 'POST_PRODUCT_OPTION_IDLE';
export const POST_PRODUCT_OPTION_REQUEST = 'POST_PRODUCT_OPTION_REQUEST';
export const POST_PRODUCT_OPTION_SUCCESS = 'POST_PRODUCT_OPTION_SUCCESS';
export const POST_PRODUCT_OPTION_FAILURE = 'POST_PRODUCT_OPTION_FAILURE';

/**
 * Product images
 */
export const GET_PRODUCT_IMAGES_IDLE = 'GET_PRODUCT_IMAGES_IDLE';
export const GET_PRODUCT_IMAGES_REQUEST = 'GET_PRODUCT_IMAGES_REQUEST';
export const GET_PRODUCT_IMAGES_SUCCESS = 'GET_PRODUCT_IMAGES_SUCCESS';
export const GET_PRODUCT_IMAGES_FAILURE = 'GET_PRODUCT_IMAGES_FAILURE';

export const GET_PRODUCT_IMAGE_IDLE = 'GET_PRODUCT_IMAGE_IDLE';
export const GET_PRODUCT_IMAGE_REQUEST = 'GET_PRODUCT_IMAGE_REQUEST';
export const GET_PRODUCT_IMAGE_SUCCESS = 'GET_PRODUCT_IMAGE_SUCCESS';
export const GET_PRODUCT_IMAGE_FAILURE = 'GET_PRODUCT_IMAGE_FAILURE';

export const POST_PRODUCT_IMAGE_IDLE = 'POST_PRODUCT_IMAGE_IDLE';
export const POST_PRODUCT_IMAGE_REQUEST = 'POST_PRODUCT_IMAGE_REQUEST';
export const POST_PRODUCT_IMAGE_REQUEST_BULK = 'POST_PRODUCT_IMAGE_REQUEST_BULK';
export const POST_PRODUCT_IMAGE_SUCCESS = 'POST_PRODUCT_IMAGE_SUCCESS';
export const POST_PRODUCT_IMAGE_FAILURE = 'POST_PRODUCT_IMAGE_FAILURE';


/**
 * Image upload
 */
export const START_IMAGE_UPLOAD = 'START_IMAGE_UPLOAD';
export const PROGRESS_IMAGE_UPLOAD = 'PROGRESS_IMAGE_UPLOAD';
export const ERROR_IMAGE_UPLOAD = 'ERROR_IMAGE_UPLOAD';
export const FINISH_IMAGE_UPLOAD = 'FINISH_IMAGE_UPLOAD';
