export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN';
export const TOGGLE_ALERT_MESSAGE = 'TOGGLE_ALERT_MESSAGE';

export const GET_PAGES_REQUEST = 'GET_PAGES_REQUEST';
export const GET_PAGES_SUCCESS = 'GET_PAGES_SUCCESS';
export const GET_PAGES_FAILURE = 'GET_PAGES_FAILURE';

export const GET_PAGE_REQUEST = 'GET_PAGE_REQUEST';
export const GET_PAGE_SUCCESS = 'GET_PAGE_SUCCESS';
export const GET_PAGE_FAILURE = 'GET_PAGE_FAILURE';

export const POST_PAGE_REQUEST = 'POST_PAGE_REQUEST';
export const POST_PAGE_SUCCESS = 'POST_PAGE_SUCCESS';
export const POST_PAGE_FAILURE = 'POST_PAGE_FAILURE';

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const POST_PRODUCT_REQUEST = 'POST_PRODUCT_REQUEST';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const POST_PRODUCT_FAILURE = 'POST_PRODUCT_FAILURE';

export const GET_PAGE_CATEGORIES_REQUEST = 'GET_PAGE_CATEGORIES_REQUEST';
export const GET_PAGE_CATEGORIES_SUCCESS = 'GET_PAGE_CATEGORIES_SUCCESS';
export const GET_PAGE_CATEGORIES_FAILURE = 'GET_PAGE_CATEGORIES_FAILURE';

export const GET_PAGE_CATEGORY_REQUEST = 'GET_PAGE_CATEGORY_REQUEST';
export const GET_PAGE_CATEGORY_SUCCESS = 'GET_PAGE_CATEGORY_SUCCESS';
export const GET_PAGE_CATEGORY_FAILURE = 'GET_PAGE_CATEGORY_FAILURE';

export const POST_PAGE_CATEGORY_REQUEST = 'POST_PAGE_CATEGORY_REQUEST';
export const POST_PAGE_CATEGORY_SUCCESS = 'POST_PAGE_CATEGORY_SUCCESS';
export const POST_PAGE_CATEGORY_FAILURE = 'POST_PAGE_CATEGORY_FAILURE';

export const GET_PRODUCT_CATEGORIES_REQUEST = 'GET_PRODUCT_CATEGORIES_REQUEST';
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS';
export const GET_PRODUCT_CATEGORIES_FAILURE = 'GET_PRODUCT_CATEGORIES_FAILURE';

export const GET_PRODUCT_CATEGORY_REQUEST = 'GET_PRODUCT_CATEGORY_REQUEST';
export const GET_PRODUCT_CATEGORY_SUCCESS = 'GET_PRODUCT_CATEGORY_SUCCESS';
export const GET_PRODUCT_CATEGORY_FAILURE = 'GET_PRODUCT_CATEGORY_FAILURE';

export const POST_PRODUCT_CATEGORY_REQUEST = 'POST_PRODUCT_CATEGORY_REQUEST';
export const POST_PRODUCT_CATEGORY_SUCCESS = 'POST_PRODUCT_CATEGORY_SUCCESS';
export const POST_PRODUCT_CATEGORY_FAILURE = 'POST_PRODUCT_CATEGORY_FAILURE';
